apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: cloud-run-poc-pipeline
description: main application pipeline
serialPipeline:
  stages:
  - targetId: env-dev
    profiles: [dev]
    strategy:
      canary:
        runtimeConfig:
          cloudRun:
            automaticTrafficControl: true
        canaryDeployment:
          percentages: [ 50 ]
          verify: false
  - targetId: env-prod
    profiles: [prod]
---

apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: env-dev
description: Cloud Run development service
run:
  location: projects/helloworld-398318/locations/europe-west1
executionConfigs:
- usages:
  - VERIFY
  privatePool:
    workerPool: "projects/helloworld-398318/locations/europe-west9/workerPools/pool1"
- usages:
  - DEPLOY
  - RENDER
  - PREDEPLOY
  - POSTDEPLOY
---

apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: env-prod
description: Cloud Run production service
run:
  location: projects/helloworld-398318/locations/europe-west1