steps:
  # Install dependencies
  - name: python
    entrypoint: pip
    args: ["install", "-r", "requirements.txt", "--user"]

  # Docker Build
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 
           'europe-west1-docker.pkg.dev/${PROJECT_ID}/cloud-run-poc/myimage:${SHORT_SHA}', '.']

  # Docker push to Google Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push',  'europe-west1-docker.pkg.dev/${PROJECT_ID}/cloud-run-poc/myimage:${SHORT_SHA}']

  # Deploy to Cloud Run
  - name: google/cloud-sdk
    args: ['gcloud', 'run', 'deploy', 'cloud-run-poc',
           '--image=europe-west1-docker.pkg.dev/${PROJECT_ID}/cloud-run-poc/myimage:${SHORT_SHA}',
           '--region', 'europe-west1', '--platform', 'managed' ]

# Store images in Google Artifact Registry
images:
  - europe-west1-docker.pkg.dev/${PROJECT_ID}/cloud-run-poc/myimage:${SHORT_SHA}