apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: cloud-run-poc-service-prod
spec:
  template:
    spec:
      containers:
      - image: europe-west1-docker.pkg.dev/helloworld-398318/cloud-run-poc/myimage