apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: cloud-run-poc-service-dev
  annotations:
    run.googleapis.com/ingress: internal
    run.googleapis.com/ingress-status: internal
    run.googleapis.com/network-interfaces: '[{"network":"projects/helloworld-398318/global/networks/defaultvpc","subnetwork":"projects/helloworld-398318/regions/europe-west9/subnetworks/europe-west1"}]'

spec:
  template:
    spec:
      containers:
      - image: myimage