apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: cloud-run-poc-service-dev
  annotations:
    run.googleapis.com/launch-stage: BETA
    run.googleapis.com/ingress: internal
    run.googleapis.com/ingress-status: internal

spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/execution-environment: gen2
        run.googleapis.com/vpc-access-egress: private-ranges-only
        run.googleapis.com/network-interfaces: '[{"network":"projects/helloworld-398318/global/networks/defaultvpc","subnetwork":"projects/helloworld-398318/regions/europe-west1/subnetworks/europe-west1"}]'
    spec:
      containers:
      - image: myimage