apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: cloud-run-poc-service-dev
spec:
  template:
    spec:
      containers:
      - image: europe-west1-docker.pkg.dev/${PROJECT_ID}/cloud-run-poc/myimage
      - env:
        - name: var
          value: value2