apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: cloud-run-poc-service-dev
spec:
  template:
    metadata:
      annotations:
        commit: defaultShaValue # from-param: ${git-sha}
    spec:
      containers:
      - image: image1
      - env:
        - name: var
          value: value1