apiVersion: skaffold/v4beta7
kind: Config
metadata:
  name: cloud-run-poc-skaffold


build:
  local:
    push: true

  platforms: ["linux"]

  artifacts:
    - image: myimage
      docker:
        dockerfile: ./Dockerfile

profiles:
- name: dev
  manifests:
    rawYaml:
    - service-dev.yaml
- name: prod
  manifests:
    rawYaml:
    - service-prod.yaml

deploy:
  cloudrun:
    projectid: helloworld-398318
    region: europe-west1

verify:
- name: verify-endpoint-test
  container:
    name: ubuntu
    image: google/cloud-sdk:stable
    command: ["/bin/sh"]
    args: ["-c", "gsutil cp gs://europe-west1.deploy-artifacts.helloworld-398318.appspot.com/verify.sh ./verify.sh
    ; sh ./verify.sh"]