apiVersion: skaffold/v4beta7
kind: Config
metadata:
  name: cloud-run-poc-skaffold
profiles:
- name: dev
  manifests:
    rawYaml:
    - service-dev.yaml
- name: prod
  manifests:
    rawYaml:
    - service-prod.yaml
deploy:
  cloudrun: {}